
import de.mpimp.golm.robin.rnaseq.mapping.RNASeqBowtieAlignment;
import de.mpimp.golm.robin.rnaseq.mapping.RNASeqBowtieErrorRecorder;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;
import junit.framework.TestCase;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marc
 */
public class TestBowtieErrorRecorder  {
    
    public static void main(String[] args) {
        
        String[] lines = new String[] {
        "HDA00003/1      -       8453549 1158    TCATATTCATACCAAAATTCACAAAAAACGAATTAGGGAAGTCTAGTGATGTCACTTTCCATAAATGACATGTTGTTGTG        FFFFFFFFHHHHJJJJJJHHCIIJIGJJJJJJIJIJJJJJIJJJJJJJJJJIHFJJJJIJJJJJJJIHHHHHFFFFFCCC        0       1:A>T,2:T>G",
"HDA00008/1      +       8487341 715     CACATAAATTTTTCACACTTCATTAGAAACACTCAATTGATATCGAATTTAAGTTGATTGATTTAAGATTTCGCTGGCAG        CCCFFFFFHHHHHJJJJJJJJJJJIJJJJHIJJJJJJJJJJJJIJJJJJJJIJJJJIJJJJJJJJJJIIJIIIJJIHHGH        0       0:A>C,2:T>C",
"HDA0000E/1      -       8362143 287     CTCTTCGTGCTTAATCCTGTCAAAATAAAAAGGATGTAATTAATCTGATTTCTTATTATGAATAAATATTTCTCTTGGTG        HBFHEIFA=GIIIGIGJIJIGJIIJIIJJJJIGIJJIHIIGHEJJJJJIHF@HGIGGIGGIGIGFFHHFGHHFFFFF@@@        0       0:A>G,1:G>T",
"HDA00011/1      -       8609730 5138    AATTATAAACATAATTTGATTATTACCTTCGGTTAAAAGATATGATTTAATCTGCTCTAGCTTCCCTATCATTTCATGTG        GHHHEHHHGJJIJJJJIHJJJJIHFIHIHIHJHJJJJJJJJJJJJIJIJJHIIIJJJIJJJJIJJJJHHHHHFFFFFCCC        0       0:A>G,2:A>G",
"HDA00014/1      +       8632305 9326    CACTGGGTAGTGTATCCCTCATTAATAAAGCCAAGAACGACCTAGCGAAGGAAGGTCATAAGTTGTCTAGGTTGGGGGTG        BBCFFFFDHHFHHHIJJJIJJJJJJIJJJJJJJJJJJJJJJJJJJIJJJIGHIJJGIHHHHHEHFDEFEFFACEDDBD5<        0       1:T>A,2:A>C",
"HDA00016/1      +       7079535 62      CACCGTGTGTGCTGTCGAAAAGCGGTGATGTCATGCCACGCCCGACGTAGTCCGACCGTGTGTGCTGCCCAAGGGCGGTG        BCCFFDDFHHHHHJIJJJJJJIJJJGHIGIJIJJJJJJIJIJJJIJJJHHHHHFFDDDDDDDBDDCDDDDDDDDD@BD<@        0       0:G>C,1:G>A",
"HDA00017/1      -       8543290 3186    AGCTCGTTTGGGTGTCTGGCTAGAAGACTCTCCAAAGGGTGGTTTCGTGATTCGCCATAACTCCTAGTCATATTTAGGTG        38,;>=BB@?;>;DDDEA=AFEEEEEEC;C@EFFF=A6ADGDEGEIGC::DIGG?<?<CA;CF;FEEBFDBC;DDAD@@@        0       2:T>G",
"HDA0001C/1      +       8579249 2989    CACAGAGAATAACTAACAAAAATTGTAAATTAAAGGCGGGGGTGACACCAAAGTGTCAACTATTGATTTGGGGTTTTTGT        CCCFFFFFHHHHHJJJJJJIIIJJJHGIJIJGGGJJIIJJFD;@BCCDDDDDDCCDCCCCDDDECDEDEC>@D;9<8@BB        0       0:T>C,2:A>C",
"HDA0001L/1      +       8648654 1621    CACCATGAATCAAACATACATGCTTATGTGCTATCCAACCAACCAAGCAACTATAGGAGGTATATTGATCCTCCAGATCA        CCCFFFFFHHHHHJJJJJJJJJJJJJJJFIIJJJJJJIJJIJJJJJJJJJJJJJJJJJJG;FHJJJJJJJJJIHHHGHFF        0       0:T>C,2:T>C",
"HDA0001P/1      +       8612954 5718    CACGTGCCTTATTTATTTTCATGTGATTATGTGGGTGTAATGAGTTTATGATGTCATTATATGTTTGATATTAATGTTTA        CCCFFFFFHHGHHJJIJIIIHHHHHCHIGJJFIII?FGGIIIFHHIIIJJJIHIJIIJIHICEHGIIEGBHICFHFHIJI        0       0:T>C,2:T>C",
"HDA0002A/1      +       7812604 122     CACAGCACACAACTCATTTTCTATATGATTAAAAGACATTATTATCATCAACATAATTTTAAAACAACTCGAGCGAAGAT        @@@DDDDDHFDHBGGBCBHGIE?FBHCHIIGEDEEEGDHFEHIEGDGHGIIGHIIFHIIGEII>GHI@GCDEHAEB89<A        0       0:A>C,2:A>C",
"HDA0002G/1      +       8468841 477     CACAATTTATATTCAAAACGGATAAATATAAATAATAAATGCAAGACAAATAGTGGTTAAAAATATGTATTTTGACCGAA        CCCFFFFFGHHHHJIJJJJJJIJJJJJIIIJJJJJJJJJJIJJIJJJJGFFHIIGHIIIJJJJJJJJIJIIJIGGCDHEF        0       0:T>C,2:A>C",
"HDA00034/1      +       8285906 221     CACATTCATAATTGTTCACCCTCAACCATCTAACATTAAGATCATCAAATGAATTAAATAGTTTAATATAACATTAAATG        CCCFFFFFHHHHHJJJJJJIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIJJIJJJJJJIJJJIIIIJJJJJJHHJII        0       0:T>C,2:G>C",
"HDA0003D/1      -       6493691 15      ATCGGCGTCGTCGCACGACATCTCATGTCGGGCGGCGGGGTGGATGTCGGGCGTGCATTGACGGAGCTATTCACGTAGTG        B>@>@DDDDDDDBDDDDDDDDDDDDDDDDDDFFJIGIJJJJIJJIJIJJJIIJJJJJJJJJJJJJJJHHHHHFFFFFCCC        0       1:G>T,2:C>G",
"HDA0003E/1      -       8641101 9143    CTTAGCTTTAGTAGTTGTAAGGGATGCTACCTTAGCCTTGCACAAGTATACTTTGAGGTAGCTTGTAAAGTAGTTCAGTG        HACGDGCGIIIIIIIIFIIIIIIIIIIHFGIIIIIIIIIIHEIIIIGHEAIHHGD@GIHHEBIEIIIHGHHHFFFFFCCC        0       0:T>G,2:T>G",
"HDA0003P/1      +       8511364 2198    CACCTCATTTTCCTAGGGTGAGGTCTTTTACCTTTACATGGCTTGCACATTAGCTACACCTATGCGGGCGCATAATTAAG        CCCFFFFFHHHHHJJJJJCGGIJEHHIJJJJJJJJJJJJJJJJJIHIJJJJJJJJJJJJIJJJJJJIHFDDDDDDDCDDD        0       0:A>C,1:C>A",
"HDA0003R/1      +       8603418 499     CACGGTCAATTCAATTCTCGATGGAAACGAAATTTTGCGAATTCTCCCCCGAACTGAAAGATCATTTCGAGATCTTTCGA        B@CFFFFFHHHHHJJJJJJJGIIIIIJJJJJJIIJJJJJIJIJHIGHIIJIJHBEAEEFFFFFEEDEECDDDDDECCCBD        0       0:A>C,2:A>C",
"HDA00042/1      +       8575803 297     CACCGTATTCGATTGCACTACATGGTTGGACAAAACCTTTTATAGCTCCACTAAATTCCGCTTTAGAAAGGGTTCATAGG        CCCFFDFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIJJJJJJJJJJJJIIJJJJJJJJJHHGHFFF@DFEE        0       1:T>A,2:T>C",
"HDA00044/1      -       8652726 4397    TTCACAAAGGAGCTGCTCAAAAAGAATGAGTAACCTTAATTCTCATAAATATGAGTGTAACGGGACTTCATGTAAGCGTG        FDHHAHHHHJJJIIEGHFIHHIJIJJIJJJJJIJJJIJJJIJJJJIJJJJJJIIJJJJJHIJJJJJJHHHHHFFFFFCCC        0       0:C>G,2:C>G",
"HDA00049/1      +       7621129 44      CACTAAAATCTAGTTAATGCATCCCAAAATTCTTCTTCTGATTCTTTCTAAAATAATCTCAATTTTTTGAATCAAAGTTG        CCCFFFFFHHHHHJJJIGIIJJJJJIJJJIJIJJJJJJJJIJJJJJJJJJJIIIIIJJJIJIIJJIJJIIJIIIIHEAHH        0       2:T>C",
"HDA0004A/1      +       6619950 27      CACGGAACGTGAGCTGGGTTTAGACCGTCGTGAGACAGGTTAGTTTTACCCTACTGATGACAGTGTCGCAATAGTAATTC        CCCFFFFFHHHHHJJJJJHHIJJJJJJJJJGIJJJJJJJFHIIHHJJJJJJJJJHHHHHHHFFFFFFDDDDDDDC>BDFE        0       0:T>C,2:G>C",
"HDA0004C/1      -       8062880 213     TTGCAATAAGGCCGTTTTGGCAAACTACTATGATATGTTATTCTTTGATTTGAATTGATTCCGCAATTTTTAGATGGGTG        EEEEEEFFFFHJJJJJJJIIGGHJJJJJJIJJJJJJJJJIIGGJJJJJJJJJJJJJJJJIJJJJJJJHHHHHFFFFFCCC        0       2:T>G",
"HDA0004U/1      -       8583847 387     TCTCAACACCTGATATTACTTTAATCAAAGCATTTTCGAAGTTCAAAACTTTTGGTTGCAGATATTACACCAAAGGAGTG        FHHEEIIHIIIJJJJIHFJJIJJIGJIJJJJJJJJJIJJJJJJJJIHHJJJJJJJJJJJJJJJJJJJHFHHHFFFFFCCC        0       0:T>G,1:A>T",
"HDA0004W/1      -       8595999 5797    TTAGTCTAAGTAGGGGTATGGGACTCTACCTGAGCCTTGCACTAGTTTTCCTTGAGGGAAGCCTTAGGAGGTTGTTCGTG        EEEEEFFFFFFHGHHJJJIJHGCJJHGFJJJJJJJJJJIIHJJJJJJJHJJJJJJJJJJJJJJJIJJHHHHHFFFFFCCC        0       0:A>G,2:T>G",
"HDA0004Y/1      +       8061232 127     CACCCATGAAAGCAAACATCTCATTGAATATGGTTCCTCCTCATGAACCACCACCATTGACACATCATTTGGCTCATCAA        CCCFFFFFHHHHHJJJIJJJJJJJJJJIJIJJJGIJJJJJJJJJIIJJJJJJJJJJJJJJJJJJJJJJJJDHIIHEHHHG        0       0:G>C,2:T>C",
"HDA0005J/1      +       8449192 370     CACTAAACTACTCTCTAGACAACAGACTAAAAACTATGAAAGAAAATTAGACATTACATTGAGTAAATCAAAACGAAATG        CCCFFFFFHHHHHIJJIJJJIIJJIJGIJJJFIJIGHIGGHIJIGIGIIJJJGCFGCHHHFFGDFHGIJJJICIIACEFF        0       1:C>A",
"HDA0005M/1      -       8538270 1582    CCAGTTCAGGTGTTTATTGAAAGTCATGCAGTAGGTGCCTATCTATGTCATGGTTAGAGCCAACACATTAAACTGATGTG        HHHHHIJJJIIHEGGIIJJJIIIJJJIJIJJJJJJJJIIJJJIJJJJHJJJJJJJJJJIJIIHHGJJHHHHHFFFFFCCC        0       0:T>G,2:T>G",
"HDA0005Q/1      -       8541010 2476    CATGAGATGAGACTGTCCGTTTAGGCGGGTATGGGTCTCCCGATATCTCCTATTCTTTGAACCTATGCTGCCAACATGTG        DEDDDDEEDDDDDDDFFFHHHHHJIJIHHJJIJJJIIIJJJIIHFHIIIIJGJJIJJJJIIJJIJJJHHHHHFFFFFCCC        0       1:G>T,2:A>G",
"HDA0005R/1      +       8603274 1943    CACCTAAACCACTTAATTAATTAAAGGAATTAACATTAAAATGTGCAGGAATGTCAAGACCCCCACAGACGAAACCCCGC        CCCFFFFFHHHHHJJJJJJJIJJJJJJHIIJIJJJJJJJJJJJGIIJJJJJJJJJJIJJIHIJJJJJJJJHHFFDEDDDD        0       0:G>C,1:C>A",
"HDA0005X/1      +       8615810 4863    CACGATGTTTTCGATGGTAGTAGGTCTACTATGTTAGTATTCTAAGCTTAATAGACTAGAATGGAGATAAGTTAGCATGG        ?@@FDADDHHHHHEBFGCHIIIII<CHCCFFBHFG@GCBFHHIGIIGHBFGBDHGGGBD@DFGGHIIID>FFGIIG==@E        0       0:T>C,2:T>C",
"HDA00064/1      -       8502286 1513    TCCAGACTTATCTTTTGAGGAGGAGCCTATGGTCATTGTTGGATATGCAAGTCTAGAGGTTAGGACCAAGGAGATTGGTG        HHHAAHHIIHEHGJJIIJJJJJJJIJJJJIIJIIIJJJJJJIJJJJJJJJIJJJJJJJJJJJJJJJJHHHHHFFFFFCCC        0       0:T>G,2:T>G",
"HDA00066/1      +       8608866 7012    CACTTTGTGTGTTGTATTTTTGTGCTTTGAGGACCACCACAGTTTGATGCGTTGTTGTAACAACCTGTTTAGTCGGTTCG        B@CFFFFFHFHHHIHIJJJJJJIJJJJJIIHHHIJJJJJJJJHIJJJJIIJJJJHHJIJJJIJJHHHHHFFFFFDDDDDD        0       0:A>C,2:A>C",
"HDA0006R/1      -       8473837 806     ATGACTTGACCTTCTACAATCATGTTGTTAGGAAAGAGCTATTCTTACTCATGCATGTCCTTGCCGTGTGCTTGCATGTG        EEFECFDDCHHHHHIHJJJIIIJIGJJIJJJJJJJJJJJJJJIJJHDJIJJJJJJJIGJJJJJJJJJHHHHHFFFFFCCC        0       0:A>G,2:A>G",
"HDA0006W/1      +       7885680 89      CACCATTCACGTAATGTGGTGAGTAATACAAAGAGATAATATGGTAAAGTTAATGAATGTGTTAACATCAAGATAAGAGG        CCCFFFFFHHHFHIJJHIJFGGIFJHIHJJJJJHJJJJJJJJJJHJJJJIIJIIJJJJJHIJJJJJJJIJJJJJJHHGIJ        0       0:G>C,2:A>C",
"HDA0006Z/1      +       7355359 33      CACACACACGGTCGGCAACGTCAGGCATGGTATAACATTACCGCCCTAGGACAGGACACACGGTCGGCAACATCGGGTGT        CCCFFFFFHHHFHGJJJJJJIJJJIJEIIJ?FHIIJJJJJJIJJJHHFFFFFFDCEDDDDDDD?BDDDDDDBDDBD@(5<        0       0:A>C,1:G>A",
"HDA00079/1      -       8326157 34      TATGTAGAATATATTAAATTTCCTTTGATCTTATATAGTTTGAGTTGCGTCTTATGGCTTACAAAGATTTTCTTCGTGTG        EEFFDFFFFGHGHHHHJJIJJJJJJJJJIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJHHHHHFFFFFCCC        0       0:A>G,2:T>G",
"HDA0007D/1      +       8486041 1122    CACAAAAAGACCTACTTAAGTAAATCAAGAAGATAGCGTCCATAGTAACCTCTTCAAGATTACCTAAATAGTTCTTAAGA        CCCFFFFFHHHHHJJJJJJJHHIJJJJJJJJJJJJIJJJJJJJJJIJJJJJJJJJJJJJJJJJJJJJIIJIHHHHHHHHH        0       0:T>C,2:T>C",
"HDA0007O/1      -       6486634 38      TAGACCTTCGGAATTCGAAGCTAGAGGTGTCAGAAAAGTTACCACAGGGATAACTGGCTTGTGGCAGCCAAGCGTTCGTG        DDCDBDABFDCFFHEHHIJIIGJJJJJHIJJIJIJJJIIHDIIIIIJJIJJJJJJJJJJIJJJJJJJHHHHHFFFFFCCC        0       0:A>G,2:A>G",
"HDA0007R/1      -       8593263 5371    AAACGAATCCCACAAAGAATCACAATCTCATCAATGTATATCCTTGCATAATCTTCTACCAAATAAGTAGAATTGACGTG        HE=;EHE@IHDGDIGIIIIIIHDHG@FCIGGIHGHB?DCGIGHHGGGF@HHGCHBEIGHFEDC?HGHDHGFFDBDDFCC@        0       1:A>T,2:T>G",
"HDA0007T/1      -       8611142 6907    CTGGAGTGGAACTTGATTGTCCCTGGTAGCCGCTCCTCCTCTCATCTGACCAATGTTTCTCCTAGTATTCATTCACTGTG        DCDDDDDCEEEEAEFFFFHHHHJJIIIJIJJJIIJIGIIIJJJJJJJIHIJJJJJJJJIHJJJJJJJHHHHHFFFFFCCC        0       0:A>G,1:A>T",
"HDA0007W/1      -       8597363 1904    TTATTTTCTGTTGTATTTCCTTTTAGACATCGATTATAGTTTCAGACTTATCTTGTATTCGTAGATGCTCTTGTTACGTG        CFFDCHFHIIIJJIIJJIJJJIIJJJJJJHJJJJJIJJJJJIIIFDIIJJIGJIGIJJJJIJIJJJIHHHHHFFEDFCCC        0       1:A>T,2:A>G",
"HDA0007X/1      +       8390812 625     CACTTGTGGGGAAGAGAAGCTTCACCAGTTTCTCTTCACTGTGACTCACAAGCAGTAATTTGAATTGCCAAAAATAGTGT        C@CFFFFFHHHHHJJJJJJJIJEHHIIIHGIGIIJJGGJGGCHGIJJGHCHGIIIJIJHGGIIIJIJIIDEHEFHDE@DD        0       1:C>A,2:T>C",
"HDA00083/1      -       8649584 298     AATGTTATCTTCTTGATTTACTTAAGTATGTCGTTTGATAGCCTTTGGAAGGAGAATATCATATCATTTATATGTTAGTG        HHGGHIJHIHGIJJJJIJIJJJJJIJJJJJJJJJIJJJJJJJJIHGJIIIJJJGJJJJIJJJJHJJJHHHGHFFFFFCCC        0       0:T>G,2:T>G",
"HDA0008A/1      +       8642755 3779    CACCTTTTACTCAAATTTAATAGTGTATGACCTAATCGTCATGTTCAAATCTCATTAGAGATAGAAAAAATTCTAGGAGA        CCCFFFFFHHHHHIJIJJJJIJJHJIJJJIJJJJJJIJJJJIJJJIIIJJJJJIJJIJJIJJIJIJJHJJJJJJJIHHHH        0       0:T>C,2:A>C",
"HDA00000/2      -       8474705 61      CCTACCTTAAAGTTGCCCTTTCGATTTCTTTTCCACCACAGAATGTCCTGCTGACCTCCTTCCAGTCCACTAAATCTGTG        BAC@DEEDFFFEFGHHGIJJJIJIJIIHGDIIIHHJIIJJJJJJJJJJJJJIGFJJJJJJJJJJJJIHFHHHFFFFFCCC        0       1:C>T,2:C>G",
"HDA0000E/2      +       7117015 50      CACGAAATGTTGAGTTTATTTTTGTTTTATCTTTAACGAACGAAGTGAATACACTGTTTTATCAGTTTATATATATAGCA        @@@FFF1DFHHHFHFGGIJIIIIIHHHIHHHIIGIIFBFHEGGGGIJJJJIGGIIIHGHIIJEIC@CHEHGFECEHEBCD        0       0:T>C,2:A>C",
"HDA0000M/2      -       8647068 11021   GGACTACGTCGGGCGTGGCATGCCATCATCGTCTTTGGGCAGCACACGTG      @;;664H@G<G@IGB??AGGDGJJIHBG<HCIHGA<FA?CA?BD?DB:1=      0       1:C>T,18:C>T,45:G>T",
"HDA0000O/2      +       6373876 6       CACGACGCATCAATCCGAACGTATTTTCCGCAAAAATAAATAGATGAGTATATTTTTTTCAATTACGAGATCGAATTTCA        CCCFFFFFHHHHHJJJJIJJJHIIJJJJJJJIIIIIJJIJIJIIJJGI@EEHEHHHHFDDDDEEDDDDDDDDDDDDDDDD        0       0:A>C,2:T>C",
"HDA0000V/2      +       8557416 1701    CACGTTGTTAATTGTTGCTATTATGATTAAAGTATAATGGTTTAATCAAAATTAATTAAAAGCATGCTATTTACTAAATA        BCCFFFFFHHHHHJIIJJJIJJJJJJJJJJJIIIJJIJJJHJJJJJJIJJGIIJJIJJIJJIGIJJJJIJJJIJJIJIHG        0       0:T>C,2:A>C",
"HDA00012/2      -       6717949 44      GACAACACATACAATTTGACGATGTCGGGCGTCGTATGTCCGCATGATCCTTGAGAAGCACACACGGTAGGATTACAGTG        DCDDCCBEDDCDDDDDDDDDEDDFFFHJIGJJJJJJJJJJIJJJJJJJJJJJJIIIHGFHEGGGIJJHHGHHFFFFFCCC        0       2:T>G,60:T>C",
"HDA00015/2      -       8644956 5561    CATGGGATCGTTTCCCATTATCTCGGATAGAGGTTACGAATTCAGTTCTCATTTTTGGAGGTCTTTTCAAAAGGGGCGTG        DDDDDDDDDFFFFFHHHHHHJJJJJJJJIHJJJJJJJJJIJJJJJJJJJJJJJJJJJJJJJJIJJJJHHHHHFFFFFCCC        0       1:A>T,2:T>G",
"HDA0001F/2      +       8650110 16698   CACGAACATAATCTCATAGAAAGTCTATAATATGTCTCATATTAAACCATCTAAAACAAATACAACAATTGGGCTTAACC        CCCFFFFFHHHHHJJJJJHHIJIHIIIIIJJJJJGIJJJJIJJJJJJHIJIHIJJJJJJJJJGIJFHIIHHIJIJHHHGH        0       0:T>C,2:G>C",
"HDA0001M/2      +       6659451 30      CACGGTTGATTTCGATGTAATTCTGGGTATGATATGGCTTTCTCCGAATTTTGCAATCTTAGATTGTAATGCTAAAACTG        @@CFFDDFHHHHHJIJJGGIJJIJJJIFHIJJJJJJHJJJJJJJJJIJIJGGIHJJJJJJJJIJJJIIIIIJJIHHHFFF        0       0:A>C,2:T>C",
"HDA0001P/2      +       7909535 25      CACGACACGACGGACCCCATGATGGTCCGTCATAGTCATGACGTGCCATCACCTGGCCCGTCGTGTGTCACTGTTACTAT        BCCFFFFFAFHFCGHHIEGBHEGGGHEHDBCGHIJIIG@@HG7;AAEECE;@C>?;;@?8;?B;@??<CDC@@:AACDDD        0       0:T>C,2:A>C",
"HDA0001W/2      -       8516324 204     TTTTTGGTGTGTTTGAAGGAGGCATATGAATACTTACTTCATGTCTTACCTTAGTAAGTCTTAGGATAATTCTGAGGGTG        HHHJJJJJJJJJJJJJIIJJJJJJJJJIIGHGJIHFJIJJJJJIHIIHJJJJJJJJHHHIJIJJJJJHHHHHFFFFFCCC        0       1:A>T,2:T>G",
"HDA00024/2      +       8620028 878     CACGGGAAACCTTTCTCCAAATAACCGAAGACATGATTACACAAGAACAAGCCGTCACCACTCAAGCACAAGCCCCGACG        CCBFFFFFHHHHHJJJJJJEFHHIIJIJJJJJJJJJJJJJJJJJJJJIIJHIIJJJHHHHFFFFFEEEEEDDBDDDBDDD        0       0:T>C,2:A>C",
"HDA0002B/2      +       7967664 232     CACATACACGATCGGACGACGTTGGGCGGGGCATGTTATCATCGCCCTTGGAGTGCACACACGGTCGGATGATGTTGGGC        CCCFFFFFHHHHHJJJJJJJJJJJJJIJJDDDDDDDEEEDEEDDDDDDDDDDDABDDDDDDDDD?BBD@BDCDDDDCDDD        0       0:A>C,23:T>G",
"HDA0002O/2      -       8651618 8190    TATTTAAATCATTGTCCTTTTTACTCAAGTGAACTACTTCATAACCCATATCCATGTTTATTTCTTAAAGGTTAAGGGTG        FHGIIJIIIIGJJIIJIGIHFGFGIGHHHFIHIHGGJIJIIIHDIHEGIHFIIHGIGJIHJIJJJIIHHFHGFFFFDCCC        0       1:A>T,2:T>G",
"HDA0002W/2      -       6863442 29      CGACCGTGGAAAGCCCGTGTAGCCATTGGACAAATTACACTGTCGAACAAAGTCGTGTGTGGCATGCCATCATCGCCGTG        BB?DDDEDDDDDDDDDEEEEEFFFFFHGFEHHHJHEGHDJIJJIJJIJIJJIIIJJIJJIJIGIJJIFHHHHFFFFFCCC        0       0:A>G,2:C>G",
"HDA00030/2      -       8599789 1042    TTTGGCCCACTGCAGCTGTGTCTCATAGATTTTTCAACTGGTGTTTCATCTCTAAACACCCCTACCTCCCTAGTTCTGTG        DBBDDCA@;EFFFFFHHHHJIJJIGJJIHGIIIGGC8JIJJIJIGJJIIJIIJIJHF@JJJIIHIGHHHHHHFFFFFCCC        0       0:C>G,2:T>G",
"HDA00033/2      +       7564648 93      CACAGTCGTAGAGCTTGAAGATCAGGGTATTTGGAAAAAGGTTCGAGCTAAAGAATACTCTGTCATTGAGCAGCTGAGTA        CCCFFFFFHHHHHJJJJJJJIJJIJJJFGHJJJJJJJJJJJHIJJJJIJJCHIJJHIJJJIJIJJJJEFEHHHFFFFFCC        0       0:A>C,1:C>A",
"HDA0003M/2      -       8535056 1962    TATCTTTGTTGAATACAGGGTATCTTCATCACGCGACTGTTGACAGACCTCACTTAGGACATCGGTGAAGGACATCGGTG        DDDDDDDEEEFEEEEFFFFFHHHHHHJIHEJJJJJJJJJJIHGJIIGJJJHGJJJIIJIJJJJJJJJHHGHHFFFFFCCC        0      ",
"HDA0003O/2      -       8572996 3326    ATAACCACATGGTTCAGGACTGGAGGAACTGCGTTGGCATTGTGTGCATAAGCATTCCTTGCATAAGTTCTACGAAGGTG        ECA;FDDEDHHHHJJIJJJHIJJJJJHFF@IJJJJJJJJIJJJJIIIJJHIJIJIJIJIIIGIJJJJHHHHHFFFFFCCC        0       1:G>T,2:A>G",
"HDA0003V/2      +       8442118 701     CACGCTTCTTTCATGCACCATAAGACGGGAAATGTTCATGTTGTCATGAAGCATGGCCAAATGTCACTCCTTTTGTAAGT        BCCDADDAHHHFFIGIJA@BCHIEFHG<E@HHGD::*??BGF<F?FDAFHGCB@<8====CCFH>CEGIEEHHHH@BEC.        0       1:T>A,2:A>C",
"HDA0003Y/2      -       8645706 8894    AAAAGACAATAGAAACTAGAGGAGAGTTGGTGGCAAACATGGTCAAAAAATCATAGGTATCTTAGAAAGTGGTCCCCGTG        DDEEEEEEEFFFFDCFHHHHHHJJIJJIHHJJIJJJIIJJJJJJJJJJJIIJJJJJJJIHJJJJJJJHHHHHFFFFFCCC        0       0:T>G,2:A>G",
"HDA00044/2      -       8644950 6537    GCTACACATGAGAGAGAAGAACACATGAAGATACAATATCCAAACTTGTTTCGAGACTAGTCTAGTGTATATTTCGAGTG        HHEJJIIGIGJHGGIIIJJJJJIHCJJIHFJJJJJIJIHJJJIIJJIJJIIHJHGJJJIIJJIJIJJHHHHHFFFFFC@B        0       1:A>T,2:A>G",
"HDA00049/2      +       8535590 2199    CACCTAATATAAGGACCTTATAGACTCATTAATCATACTTGAACATATAAAACCGCATATGAGGCACATAGGTGACTTAG        CCCFFFFFHHHHHGHJIJJIHGHHGHIGIJJJJFJIIIJJIJJJIIIIJGFHHJJJJJJJEIIGJGJJIIGHHHHHHFFF        0       0:T>C,2:A>C",
"HDA0004P/2      -       8649860 8656    TCCTGTTAGGGATCTTCTTGTGATGATATGCTCCCAGAATGACGGTGAACATCGGTCAGCTGTGGTTTCATTTATTGGTG        BDDDEEEEEFFFFFFHHHHJJJJIJJJJJGJJJJJJJJJJJJJIJJJJJJJIJIJJJJJJJJJJIJJHHHHHFFFFFCCC        0       2:T>G",
"HDA00057/2      +       8606750 1938    CACGTATTAAATACTTATATACAAACTTAAATTACCCAAAGGACCCCTAAATAACCTCTAATATTGTTATTTGTAAGTGT        CCCFFFFFHHHHHJJJJJJJJJJJJJJJJJJJJJJJJJIJJJJJJJJIIJHIJJJJJJJJJJIIIJJJJJJJJJJJJIJH        0       0:T>C,2:A>C",
"HDA00059/2      +       8652988 17466   CACGTCTTTGAACGCAAATAGCAGCTAAAGCAATCAGGTCGAGGGCAAGTCTCCTGGGCATCAAGCTTTGGTGTGAGAAA        CCCFDDFFHHHHHJJJJJJJJIJJJIJJIJJJJJJJJIHJJJJJJJJIJJFHJJJIJHHGHHFFFFFEEEE=BABCDCDD        0       1:G>A,2:A>C",
"HDA0005B/2      +       8641393 3625    CACTGTTGAGGTGTTCATCGATGATTTCTATGTGGAAGGTGACTCTTTTGATCGGTGCTTGGATAATTTGGCCGAGGTAC        CCCFFFFFHHHCFGIJIJJJIJIHJIIIJJJJHIJIIJJGHIIIJJJJJJJJJIJ?DHIJIIHIIJJIIGIJJHEFD3@C        0       2:T>C",
"HDA0005D/2      -       8475929 1086    CCTGAAGTAGACTGAGGGATTCATCTTTGTGAAATCTCTCAGTCTTCTAGCCATGGTGCTAGCATGTGGTTTCTCCGGTG        ECDEFFFFFEBHFGHHHGJJJIIHGJJIHHJJJJIJJIJFJIIJJJJJJJJJJJJJIGJJIJJJJJJHHHHHFFFFF@CB        0       0:A>G,2:T>G",
"HDA0005X/2      +       8561386 2987    CACGGGCGATAACTCTTAACTTGAAGGCGTCAAGGCACTGATGGACAGCAAGAATCTTCCGCTCAGTCTGCTGGGCAATA        =+=BDDD@DFHHBFHIJHHHGHG@DG?B@@@D6BFGCG@A=8@>==DCEH?EHEDDFEDD><9?;C@AC>@>CCD?CD>C        0       0:G>C,1:C>A",
"HDA0006H/2      +       8540608 2346    CACTGAAGTATATGTTTATGTAAAGCATGATAGTGTGTGAAGTATGATGAATGTGTGTATGAGCATGTATAGAAGTCAAT        BCCFFFFFFFHHHJGIJJJJIJJJJJJJJJJJJHGJHCGHIJHIJJJJJJHIIIJFHHIJIIIJJJIBDHJJJJJHIIIJ        0       0:A>C,2:A>C",
"HDA0006I/2      +       6372878 24      CACCGTGCGTGCAGTCCAAGGGCGGTGATGTCACGCCACGCCCGACGTAGTCTGACCGTGTGTGCTGTCCTAGGGCGGTG        BBCFFDDDDDFHHJIGIBHGGGIGG?DEGGGGGGHEDGHHBHDB<BB>BDBDCC@CCD5AAA?ACDC>CCCCA?AC<@)9        0       0:G>C",
"HDA0006W/2      -       8591519 4691    TTAAGGCAAGATGTTCTCAAAAGGTAAAAATAATGTAATTAAGTGAACTTTTACTAGGATGACCTAAGGGATTTTGCGTG        GHHHHJIJJJJJJJJJJJJJJJJJJJJIGHIJIJJJJJIHJJJJJIHJJJJJIJJIIIHGHFJJIJJHHHHHFFFFFCCC        0       0:A>G,2:T>G",
"HDA00072/2      -       8648452 15988   TTCATTAATGGTTGTGTGGATTCTGAAAAAGGTTGCAACCTTTCAAAACATGTTTCTCTTGCCTATAAATACCATTTGTG        FFFGHHHHHJJJJJJJJJIJIJJJJJJIHHJJJJJJJHJJJJJJJJJJJJJJJJJJGJJJJJJIJJIHHFAHFFFFFCCB        0       0:T>G,2:A>G",
"HDA0007A/2      +       8313900 538     CACTCTTCTCTATCTCGTAGGTTCTCCACTTACCTTGCTATACATAGACCATCAACCTTGATATGTCCATATCGCATATT        CCCFFFFFGHHGHJJJJEHIJHHHHJJGIJJJJJJJJJJJJJJJJIJJIIHIJJJJIHIJGIIJJGIIIJIIIIIIGHHH        0       0:T>C",
"HDA0007H/2      -       8615444 7782    AGGACAGACGACGGTCTGTCCTGCACAACCCTCGACGGTATCAGAGACTCCCAAAAACTTCAGCTTAGAAAAATTGGGTG        DDDCDDDDDDBDDEEDEFFFFHGHHIHDIJJJJJJJJJJJJJJJJJIJIJJJJJJJIIJIJJJJJJJHHHHHFFFFFCCC        0       0:A>G,2:T>G",
"HDA0007K/2      +       7920545 157     CACGCCGTTCACTGTCCGATCAGCCATCAGTAGCTGCATTGCAGTGGGTTTTGGATCCCCCAAACCCAACTTCTTATAAA        CC@FFFFFHHGHFIGHJIJJJIJJJIGIJJIIIJJIIIIIGHGHHIII<FFFFIGHIEHHFDEEDDDDDDDDDCDDDDEC        0       0:T>C,2:G>C",
"HDA0007S/2      -       8518764 1505    TAACATGCAATGGAAGCTAGGAAAGTCGGTTCTCCCTTCTTTAGGCCCTTCAAAATCTGCATAGTCGATAAGTGGGCGTG        EECCDADCEDCCEEECFDEFFFFEHGHGF@IIGIJJIHGB@CIIJIJHHFJIGHF@HFCDHHGGHIIHHHHFFFFFFCCC        0       2:A>G",
"HDA0007X/2      -       8187078 315     AGGATAAAGTATGCAAACTAAGAAAGTCCTTGTATGGACTAAAACAAGCACTTAATCAATGGTATGAAAAATTTAATGTG        IHDHEJJGIJIJJJIIIIHJIJIHDHGIHFJIIHGIIHJJJJJIIIJIHFJFJJHHIHGDIGJJIJIHHHHHFFFFFCCC        0       0:C>G,2:A>G",
"HDA00084/2      +       6286922 9       CACGACATCATCGCCTTTGGGGAGCACACACGATCGAACGACGTCGGGCGTGGCTTGCCATCATCGCCTTTGGGCATCAC        C@BFFFFFGHHHHJJJJJJJJJIIJJJJJJJJGIJJIIJJJJHHFFDDDDDBDBDD@8?A>AAC3?<>>;C>A9???C:3        0       2:T>C,76:G>T",
"HDA0008B/2      -       8654202 14294   AACCTGGATAAAAAATATTTTTCAAACTCACCGAAAGAACCTTTTTTTCCCTATGAGATTTTACGAATCGTTTGGACGTG        CACCDCCDDDEEEFEEEFFFFFHEHEEACJIJIJJJJIGIGIIDIHFFIJIIGHIJIGJJIJIJIJJHHHHHDDDFFC@B        0       2:A>G",
"HDA0008J/2      -       8580723 3452    GGGGAACGATCTAGACATTGCACAATAGGCTTTGAAGGTGTTAGTGAGAGTCCCTAGGTCTTCTCCAAGACCATTACGTG        EC?ECA=4IHD;@F@IHIGIFCFBCGEHDBHHHEJIJIICGIIJIGJIGGFJIGHFBHBGHGGHHFDHHBDFDFEDD?B<        0       2:T>G",
"HDA0008K/2      +       8450705 1267    CACACATTTTAGGTTTTGGTCGTTGAAAGACTTTTCGAGACGACTTTGAAGAAGACTTGAAATTCTTAATCATCCAAGTT        CCCFFFFFHHHHHEHIJJIFIIIIIGJJJIJGHJJJJJJIIJHIJJIIIHFHIJJIHIIIHHHHHHFFFFFFFEEEDEED        0       1:C>A,2:A>C",
"HDA0009A/2      +       8431976 230     CACATCGTGTATATTTTCCAAGGGCGTTGATCACATGCCACACCCGACGTAGTCCGATCGTGTATGCTATCCATGGGAAA        B@CFFFFDHHHHGJJJJJJJHJJJIIIJJJJJIJJJJJJJJJJJJIHIIHGHHHHFBDDDDDBCDECECDCDCDDDDCCB        0       1:C>A,2:G>C",
"HDA0009H/2      +       7841386 77      CACACGGTCAAACGACATCGGGAGTGGCATGCCATCATGGCCCTTGAACATTAAACACACAGTCGATCGACGTTGGGAGT        CCCFFFFDHHHHHJJJJJJIJJGHGHIJJJJJJGIIAHIJIJIHHIHIIIHEHHHHHHFFBBCECBBDBDDD@BDDDBBB        0       2:A>C",
"HDA0009I/2      -       8523940 1892    AACCGAGACCCTTAACAAATTTTTCAGATTTTGTCTATGTCAAATGCTCTCCTATTTTTAGTCAATTTAGGAGGGGCGTG        CCFFDFC?EFCHGIIIJIIJJIGGGJIIGFIGBCGEGGIEJJHGIJIJJJJIEIIIGGGGIIFIIGJHDHHHFDFDD@CB        0       0:T>G",
"HDA0009P/2      -       8575185 4388    CTTAGGATTGGCTGGTTATTATCGCAGGTTCGTGGAGTGTTTTTTTCCATTGCTGCCTCACTGACCGATTTGACTAAGTG        CACCDCDCDBBDCCCDEDDDDDDFBFFHIHJIIIIJJJJJJJJJJIJJJJJJIIHGHJIHJJJIIJJGHGHHFFFFFCCC        0       0:A>G,1:A>T",
"HDA0009X/2      +       6845835 6       CACAGCACACACGCTCAGACGACGTCGGGCGTGGCATGTCATCATAGCCCTTATATATCACACACAATAGGTCGACCTCG        C@@FFFFFHHHHHJJIJJJJJJJJHJJJIJJIJHHHFFFFFFEDECDCEDDCCDDDDDEEDDDDDDDDDCC:>BDDBDDD        0       0:T>C,2:T>C",
"HDA000A1/2      -       8608920 4940    ATCTCAAGGATCAAGTGTTATATGTAGGTTTTTCTAACTGTGAGTTCTATCCTGAACCCGTGGTGTTCTTTATCCACGTG        DDEFFFFFFHHHHHHJHIIIJJJJJJJIHFJJIJIGFJJJJJJJJJJJJIJJJIHGJJJJJJJIIJJHHHHHDFFDFCCB        0       0:T>G,2:A>G",
"HDA000AQ/2      +       5919466 2       CACAGAAAAGGAACTGAAAATCAAGTTGCTGATCACTTGTCTCGTCTAGAGGATGAAGCTATGAGAGAGTTAGGGGATAA        CCCFFFFFHHHHDCFIIIJJJJJJIJJJJJJJJJJJJJJIJJIJJJJIJJIHGIJJGJJIIJIFIFHEH@GHEEHHEFFE        0       0:G>C,2:T>C",
"HDA000AV/2      -       8557842 2934    ATGGGTAAAAATGGATTGGGAAAGAAATGAGTTGGATAAAATACTAGTTTACCTACATTTTTATAAGTAAATAGTACGTG        JJIIGIJIJJJJJHJJJIHHJIHIJJIJIHJIJJJJJJJJIIGJJJJJIIHJJJJJJIJJJJJJJJJHHHHHFFFFFCCC        0       0:T>G,2:T>G",
"HDA000B2/2      +       8494517 1215    CACCGGTCATGTGGAAGTTGTTTAAGATAGCCTTCCTGGAAAGATTTTTCCCCAGGGAGATGAGATAGTCAAATGTTGAG        BCCFFFDFHHHHHIIIIGHIHHJJJIIEIJJJIJJJJJJGIJJJIJJJJJHIIIJJJGJIIJJJGHHHHGEHFFFDFFEE        0       0:T>C,1:T>A",
"HDA000BK/2      +       8521506 2046    CACGTCACATCTATTTTATGGTGAAGAAAGTGCACCCTATCTATTACATGTTGAAGTTGGAGGAGGCTGACGTAGAAAGA        @CCFDFFFHHHHHJJJJGJJJHHCEHIJIJFHHGIJJJJJJJJDIGIJIIIEHBFGFFGIHJIEHJJJIJJHHHHFFFFE        0       0:T>C,2:A>C",
"SRR392122.1582614 HWI-EAS85_7_FC20580AAXX:3:89:374:403/1	-	AT2G39730	933	CGTATCGGTGTCTGCAAGGGTATCTTCAGAACTGA	II=I>III>I?GHIIIIIIIIIIIIIIIIIIIIII	0	"

        
        };
        
        RNASeqBowtieErrorRecorder rec = new RNASeqBowtieErrorRecorder();
        
        for (String line : lines) {
            RNASeqBowtieAlignment ali;
            ali = new RNASeqBowtieAlignment(line.split("\\s+"));
            rec.recordAlignment(ali);
        }        
        
        
        System.out.println(rec.getMismatchRates());
        
        JFrame frame = new JFrame();
        JPanel panel = new JPanel();
        frame.add(panel);
        panel.add(rec.getMismatchRatesPlot(new Dimension(400,300), "Positional mismatch rates"));
        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    
    }
    
}
