/*
 * CelFileInfoPanel.java
 *
 * Created on 9. Juni 2008, 17:36
 */

package de.mpimp.golm.robin.GUI.affy;

import affymetrix.calvin.exception.UnsignedOutOfLimitsException;
import affymetrix.fusion.FusionTagValuePair;
import javax.swing.JFrame;
import affymetrix.fusion.cel.FusionCELData;
import java.util.ArrayList;
import java.util.List;
import org.apache.commons.lang.StringUtils;
import org.openide.util.Exceptions;

    
/**
 *
 * @author  marc
 */
public class CelFileInfoPanel extends javax.swing.JPanel {

        private FusionCELData celData;
    
    /** Creates new form CelFileInfoPanel */
    public CelFileInfoPanel(FusionCELData data) {
        initComponents(); 
        detailPanel.setVisible(false);
        algParPanel.setVisible(false);
        datHeaderPanel.setVisible(false);
        celData = data; 
        populateInfoPanel();
    }
    
    public void populateInfoPanel() {               
        celData.readHeader();        
        List<FusionTagValuePair> params =  celData.getParameters();
        for (FusionTagValuePair par : params) {
            System.out.println("Tag"+par.getTag()+" Value:"+par.getValue());
        }
        
        fileNameField.setText(celData.getFileName());
        chipTypeLabel.setText(chipTypeLabel.getText()+" "+celData.getChipType());
        columnsLabel.setText(columnsLabel.getText()+" "+celData.getCols());
        rowsLabel.setText(rowsLabel.getText()+" "+celData.getRows());
        
        //TODO complete the list of displayed parameters
        
        
        algParField.setText(StringUtils.join(StringUtils.split(celData.getParams(), ";"),"\n"));
        algParField.setCaretPosition(0);
        try {
            datHeaderField.setText(StringUtils.join(StringUtils.splitByWholeSeparator(celData.getDatHeader(), "  "),"\n"));
            datHeaderField.setCaretPosition(0);
        } catch (UnsignedOutOfLimitsException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        fileNameField = new javax.swing.JTextField();
        chipTypeLabel = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        offsetYLabel = new javax.swing.JLabel();
        algorithmLabel = new javax.swing.JLabel();
        gridCornerULLabel = new javax.swing.JLabel();
        gridCornerLLLabel = new javax.swing.JLabel();
        columnsLabel = new javax.swing.JLabel();
        rowsLabel = new javax.swing.JLabel();
        swapXYLabel = new javax.swing.JLabel();
        totalYLabel = new javax.swing.JLabel();
        axisInvertYLabel = new javax.swing.JLabel();
        totalXLabel = new javax.swing.JLabel();
        gridCornerURLabel = new javax.swing.JLabel();
        axisInvertXLabel = new javax.swing.JLabel();
        gridCornerLRLabel = new javax.swing.JLabel();
        offsetXLabel = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        algParPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        algParField = new javax.swing.JTextArea();
        datHeaderPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datHeaderField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(214, 232, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.jLabel14.text")); // NOI18N

        jLabel16.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.jLabel16.text")); // NOI18N

        jToggleButton1.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.jToggleButton1.text")); // NOI18N
        jToggleButton1.setActionCommand("null");
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.jToggleButton2.text")); // NOI18N
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel17.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.jLabel17.text")); // NOI18N

        fileNameField.setEditable(false);
        fileNameField.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.fileNameField.text")); // NOI18N
        fileNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fileNameField.setDragEnabled(false);
        fileNameField.setEnabled(false);

        chipTypeLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.chipTypeLabel.text")); // NOI18N

        detailPanel.setBackground(new java.awt.Color(214, 232, 255));
        detailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.detailPanel.border.title"))); // NOI18N

        offsetYLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.offsetYLabel.text")); // NOI18N

        algorithmLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.algorithmLabel.text")); // NOI18N

        gridCornerULLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.gridCornerULLabel.text")); // NOI18N

        gridCornerLLLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.gridCornerLLLabel.text")); // NOI18N

        columnsLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.columnsLabel.text")); // NOI18N

        rowsLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.rowsLabel.text")); // NOI18N

        swapXYLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.swapXYLabel.text")); // NOI18N

        totalYLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.totalYLabel.text")); // NOI18N

        axisInvertYLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.axisInvertYLabel.text")); // NOI18N

        totalXLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.totalXLabel.text")); // NOI18N

        gridCornerURLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.gridCornerURLabel.text")); // NOI18N

        axisInvertXLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.axisInvertXLabel.text")); // NOI18N

        gridCornerLRLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.gridCornerLRLabel.text")); // NOI18N

        offsetXLabel.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.offsetXLabel.text")); // NOI18N

        org.jdesktop.layout.GroupLayout detailPanelLayout = new org.jdesktop.layout.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(totalXLabel)
                    .add(totalYLabel)
                    .add(offsetXLabel)
                    .add(offsetYLabel)
                    .add(algorithmLabel)
                    .add(columnsLabel)
                    .add(rowsLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 179, Short.MAX_VALUE)
                .add(detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(gridCornerLRLabel)
                    .add(gridCornerLLLabel)
                    .add(swapXYLabel)
                    .add(axisInvertYLabel)
                    .add(axisInvertXLabel)
                    .add(gridCornerULLabel)
                    .add(gridCornerURLabel))
                .add(142, 142, 142))
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detailPanelLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(detailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(detailPanelLayout.createSequentialGroup()
                        .add(axisInvertXLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(axisInvertYLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(swapXYLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(gridCornerULLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(gridCornerLLLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(gridCornerURLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(gridCornerLRLabel))
                    .add(detailPanelLayout.createSequentialGroup()
                        .add(columnsLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rowsLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(totalXLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(totalYLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(offsetXLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(offsetYLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(algorithmLabel)))
                .addContainerGap())
        );

        jToggleButton3.setText(org.openide.util.NbBundle.getMessage(CelFileInfoPanel.class, "CelFileInfoPanel.jToggleButton3.text")); // NOI18N
        jToggleButton3.setEnabled(false);
        jToggleButton3.setFocusable(false);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        algParField.setColumns(20);
        algParField.setRows(5);
        jScrollPane1.setViewportView(algParField);

        org.jdesktop.layout.GroupLayout algParPanelLayout = new org.jdesktop.layout.GroupLayout(algParPanel);
        algParPanel.setLayout(algParPanelLayout);
        algParPanelLayout.setHorizontalGroup(
            algParPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        algParPanelLayout.setVerticalGroup(
            algParPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        datHeaderField.setColumns(20);
        datHeaderField.setRows(5);
        jScrollPane2.setViewportView(datHeaderField);

        org.jdesktop.layout.GroupLayout datHeaderPanelLayout = new org.jdesktop.layout.GroupLayout(datHeaderPanel);
        datHeaderPanel.setLayout(datHeaderPanelLayout);
        datHeaderPanelLayout.setHorizontalGroup(
            datHeaderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        datHeaderPanelLayout.setVerticalGroup(
            datHeaderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel17)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fileNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(chipTypeLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 322, Short.MAX_VALUE)
                .add(jToggleButton3)
                .add(20, 20, 20))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 139, Short.MAX_VALUE)
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton2))
                    .add(detailPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(algParPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(datHeaderPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(fileNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(chipTypeLabel)
                    .add(jToggleButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jToggleButton2)
                    .add(jLabel16)
                    .add(jToggleButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(datHeaderPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(algParPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(detailPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    algParPanel.setVisible(jToggleButton1.isSelected());
}//GEN-LAST:event_jToggleButton1ActionPerformed

private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    datHeaderPanel.setVisible(jToggleButton2.isSelected());
}//GEN-LAST:event_jToggleButton2ActionPerformed

private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
    detailPanel.setVisible(jToggleButton3.isSelected());
}//GEN-LAST:event_jToggleButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea algParField;
    private javax.swing.JPanel algParPanel;
    private javax.swing.JLabel algorithmLabel;
    private javax.swing.JLabel axisInvertXLabel;
    private javax.swing.JLabel axisInvertYLabel;
    private javax.swing.JLabel chipTypeLabel;
    private javax.swing.JLabel columnsLabel;
    private javax.swing.JTextArea datHeaderField;
    private javax.swing.JPanel datHeaderPanel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JLabel gridCornerLLLabel;
    private javax.swing.JLabel gridCornerLRLabel;
    private javax.swing.JLabel gridCornerULLabel;
    private javax.swing.JLabel gridCornerURLabel;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel offsetXLabel;
    private javax.swing.JLabel offsetYLabel;
    private javax.swing.JLabel rowsLabel;
    private javax.swing.JLabel swapXYLabel;
    private javax.swing.JLabel totalXLabel;
    private javax.swing.JLabel totalYLabel;
    // End of variables declaration//GEN-END:variables

}
