/*
 * RScriptEditor.java
 *
 * Created on 19. Juni 2008, 13:36
 */

package de.mpimp.golm.robin.R;

import de.mpimp.golm.common.utilities.Utilities;
import de.mpimp.golm.robin.misc.RobinUtilities;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.JFileChooser;
import org.openide.util.Exceptions;

/**
 *
 * @author  marc
 */
public class RScriptEditor extends javax.swing.JDialog implements WindowListener {
    
    private String unmodifiedScript;
    private String modifiedScript = null;
    public final static int USER_ACCEPT = 1;
    public final static int USER_CANCEL = 2;
    private int userChoice;
    
    /** Creates new form RScriptEditor
     * @param parent
     * @param script 
     */
    public RScriptEditor(java.awt.Frame parent, String script) {
        super(parent, true);
        initComponents();
        scriptEditorPane.setText(script);
        unmodifiedScript = script;
        centerOnParent();
        this.setVisible(true);
    }
    
    private void centerOnParent() {
        Dimension parentDim = getParent().getSize();
        Point parentLoc = getParent().getLocation();
        Dimension myDim = getSize();
        
        int myX = (parentDim.width / 2 + parentLoc.x) - myDim.width / 2;
        int myY = (parentDim.height / 2 + parentLoc.y) - myDim.height / 2;
        
        setLocation(myX, myY);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        scriptEditorPane = new javax.swing.JEditorPane();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        saveToFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(RScriptEditor.class, "RScriptEditor.title")); // NOI18N

        scriptEditorPane.setFont(new java.awt.Font("Courier", 0, 13));
        scriptEditorPane.setCaretColor(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(scriptEditorPane);

        acceptButton.setText(org.openide.util.NbBundle.getMessage(RScriptEditor.class, "RScriptEditor.acceptButton.text")); // NOI18N
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(RScriptEditor.class, "RScriptEditor.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        resetButton.setText(org.openide.util.NbBundle.getMessage(RScriptEditor.class, "RScriptEditor.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        saveToFileButton.setText(org.openide.util.NbBundle.getMessage(RScriptEditor.class, "RScriptEditor.saveToFileButton.text")); // NOI18N
        saveToFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToFileButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(resetButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(saveToFileButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 439, Short.MAX_VALUE)
                        .add(cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(acceptButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resetButton)
                    .add(acceptButton)
                    .add(cancelButton)
                    .add(saveToFileButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
    scriptEditorPane.setText(unmodifiedScript);
}//GEN-LAST:event_resetButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    userChoice = USER_CANCEL;
    this.setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
    this.setVisible(false);
    userChoice = USER_ACCEPT;
    modifiedScript = scriptEditorPane.getText();    
}//GEN-LAST:event_acceptButtonActionPerformed

private void saveToFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToFileButtonActionPerformed
    String script = scriptEditorPane.getText();
    JFileChooser fc = new JFileChooser(new File(System.getProperty("user.home")));
    fc.setMultiSelectionEnabled(false);

    if (fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
        File outfile = fc.getSelectedFile();
        try {
            Utilities.saveTextFile(outfile, script, false);
        } catch (Exception ex) {
            Exceptions.printStackTrace(ex);
        }
    }
}//GEN-LAST:event_saveToFileButtonActionPerformed

    public String getModifiedScript() {
        return this.modifiedScript;
    }

    public int getUserChoice() {
        return userChoice;
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveToFileButton;
    private javax.swing.JEditorPane scriptEditorPane;
    // End of variables declaration//GEN-END:variables

    public void windowOpened(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowClosing(WindowEvent e) {
        this.dispose();
    }

    public void windowClosed(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    

}
