/*
 * ShowWarningsDialog.java
 *
 * Created on 24. Juni 2008, 08:55
 */

package de.mpimp.golm.robin.warnings;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author  marc
 */
public class ShowWarningsDialog extends javax.swing.JDialog {
    
    private WarningsHandler handler;
    private JPanel warningsPanel;
    private boolean returnVal = false;
    private java.awt.Frame parentFrame;
    
    /** Creates new form ShowWarningsDialog
     * @param parent - the parent frame
     * @param wh - WarningsHandler holding the warnings to display
     */
    public ShowWarningsDialog(java.awt.Frame parent, WarningsHandler wh) {
        super(parent, true);
        this.handler = wh;
        this.parentFrame = parent;
        initComponents();
        initWarningsList();
        centerOnParent();
    }
    
    public void showDialog() {
        setVisible(true);
    }
    
    public boolean getChoice() {
        return returnVal;
    }
    
    private void initWarningsList() {
        warningsPanel = new JPanel();
        warningsPanel.setLayout(new BoxLayout(warningsPanel, BoxLayout.Y_AXIS));
        warningsPanel.setBackground(Color.WHITE);
        
        for (Warning w : handler.getWarnings()) {
            warningsPanel.add(new WarningsListItem(w));
        }
        
        warningsScrollPane.setViewportView(warningsPanel);
    }
    
    private void centerOnParent() {
        Dimension parentDim = parentFrame.getSize();
        Point parentLoc = getParent().getLocation();
        Dimension myDim = getSize();
        
        int myX = (parentDim.width / 2 + parentLoc.x) - myDim.width / 2;
        int myY = (parentDim.height / 2 + parentLoc.y) - myDim.height / 2;
        
        setLocation(myX, myY);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ignoreButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        warningsScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(ShowWarningsDialog.class, "ShowWarningsDialog.title")); // NOI18N

        ignoreButton.setText(org.openide.util.NbBundle.getMessage(ShowWarningsDialog.class, "ShowWarningsDialog.ignoreButton.text")); // NOI18N
        ignoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ignoreButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(org.openide.util.NbBundle.getMessage(ShowWarningsDialog.class, "ShowWarningsDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        warningsScrollPane.setBorder(null);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .add(cancelButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(ignoreButton))
            .add(warningsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(warningsScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ignoreButton)
                    .add(cancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible(false);
    returnVal = false;
}//GEN-LAST:event_cancelButtonActionPerformed

private void ignoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreButtonActionPerformed
    setVisible(false);
    returnVal = true;
}//GEN-LAST:event_ignoreButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton ignoreButton;
    private javax.swing.JScrollPane warningsScrollPane;
    // End of variables declaration//GEN-END:variables

}
