/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RNASeqSamplePanel.java
 *
 * Created on 26.09.2011, 17:50:47
 */
package de.mpimp.golm.robin.GUI.RNASeq;

import de.mpimp.golm.common.logger.SimpleLogger;
import de.mpimp.golm.robin.data.RNASeqSample;
import de.mpimp.golm.robin.misc.GUI.WorkflowModuleBorder;
import de.mpimp.golm.robin.rnaseq.parser.FastQFile;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author marc
 */
public class RNASeqSamplePanel extends javax.swing.JPanel {
    
    private RNASeqSample sample; 

    /** Creates new form RNASeqSamplePanel */
    public RNASeqSamplePanel(ArrayList<FastQFile> files, String name) {
        initComponents();
        this.setBorder(new WorkflowModuleBorder(WorkflowModuleBorder.SIMPLE_BLUE_NOARROW));
        for (FastQFile file : files) {
            ((DefaultListModel)sampleFileList.getModel()).addElement(file);
        }
        sampleNameLabel.setText(name);
        
    }

    public RNASeqSamplePanel(RNASeqSample newSample) {
        this(newSample.getInputFiles(), newSample.getSampleName());
        numberReadsPanel.setText(Long.toString(newSample.getNumberOfReads())+" reads");
        this.sample = newSample;
        
        SimpleLogger.getLogger(true).logMessage("Added new sample\n"
                + "\tSample: "+sample.getSampleName()
                + "\ttreatment: "+sample.getCondition()
                + "\twith "+sample.getNumberOfReads()+" reads in "+sample.getInputFiles().size()+" files");        
    }
    
    public ArrayList<FastQFile> getSampleFiles() {
        return this.sample.getInputFiles();
    }
    
    public RNASeqSample getSample() {
        return this.sample;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sampleFileList = new javax.swing.JList();
        sampleSelectedBox = new javax.swing.JCheckBox();
        sampleNameLabel = new javax.swing.JLabel();
        numberReadsPanel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(212, 232, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 150));

        jPanel1.setBackground(new java.awt.Color(212, 232, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(RNASeqSamplePanel.class, "RNASeqSamplePanel.jScrollPane1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 10), new java.awt.Color(0, 51, 102))); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(260, 80));

        sampleFileList.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(sampleFileList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        sampleSelectedBox.setBackground(new java.awt.Color(212, 232, 255));
        sampleSelectedBox.setText(org.openide.util.NbBundle.getMessage(RNASeqSamplePanel.class, "RNASeqSamplePanel.sampleSelectedBox.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel1.add(sampleSelectedBox, gridBagConstraints);

        sampleNameLabel.setFont(sampleNameLabel.getFont().deriveFont(sampleNameLabel.getFont().getStyle() | java.awt.Font.BOLD));
        sampleNameLabel.setText(org.openide.util.NbBundle.getMessage(RNASeqSamplePanel.class, "RNASeqSamplePanel.sampleNameLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 2, 0);
        jPanel1.add(sampleNameLabel, gridBagConstraints);

        numberReadsPanel.setFont(numberReadsPanel.getFont().deriveFont((numberReadsPanel.getFont().getStyle() | java.awt.Font.ITALIC), numberReadsPanel.getFont().getSize()-2));
        numberReadsPanel.setForeground(new java.awt.Color(102, 102, 102));
        numberReadsPanel.setText(org.openide.util.NbBundle.getMessage(RNASeqSamplePanel.class, "RNASeqSamplePanel.numberReadsPanel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(numberReadsPanel, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberReadsPanel;
    private javax.swing.JList sampleFileList;
    private javax.swing.JLabel sampleNameLabel;
    private javax.swing.JCheckBox sampleSelectedBox;
    // End of variables declaration//GEN-END:variables

    boolean isSelected() {
        return sampleSelectedBox.isSelected();
    }
}
