/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TMSlidingWindowTrimmerPanel.java
 *
 * Created on 13.09.2011, 16:27:10
 */
package de.mpimp.golm.robin.GUI.Trimmomatic.modulepanels;

import de.mpimp.golm.common.help.HelpHandler;
import de.mpimp.golm.robin.misc.GUI.WorkflowModuleBorder;
import de.mpimp.golm.robin.rnaseq.trimmomatic.TMTrimmerArguments;

/**
 *
 * @author marc
 */
public class TMSlidingWindowTrimmerPanel extends TMModulePanel {

    /** Creates new form TMSlidingWindowTrimmerPanel */
    public TMSlidingWindowTrimmerPanel() {
        initComponents();
        this.setBorder(new WorkflowModuleBorder(WorkflowModuleBorder.BLUE_SHADOW));
    }
    
    public int getMinQual() {
        return ((Integer) minQualSpinner.getValue() ).intValue();
    }
    
    public int getWindowLength() {
        return ((Integer) windowLengthSpinner.getValue() ).intValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minQualSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        helpLabel = new javax.swing.JLabel();
        windowLengthSpinner = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(212, 232, 255));

        jPanel1.setBackground(new java.awt.Color(212, 232, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()-2f));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(TMSlidingWindowTrimmerPanel.class, "TMSlidingWindowTrimmerPanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(212, 232, 255));
        jLabel2.setFont(jLabel2.getFont().deriveFont((jLabel2.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD, jLabel2.getFont().getSize()+1));
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(TMSlidingWindowTrimmerPanel.class, "TMSlidingWindowTrimmerPanel.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);

        minQualSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(20.0f), Float.valueOf(1.0f), null, Float.valueOf(1.0f)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 4, 10, 4);
        jPanel1.add(minQualSpinner, gridBagConstraints);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()-2f));
        jLabel3.setText(org.openide.util.NbBundle.getMessage(TMSlidingWindowTrimmerPanel.class, "TMSlidingWindowTrimmerPanel.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel3, gridBagConstraints);

        helpLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/mpimp/golm/robin/resources/QuestionMark.png"))); // NOI18N
        helpLabel.setText(org.openide.util.NbBundle.getMessage(TMSlidingWindowTrimmerPanel.class, "TMSlidingWindowTrimmerPanel.helpLabel.text")); // NOI18N
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(helpLabel, gridBagConstraints);

        windowLengthSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(4), Integer.valueOf(4), null, Integer.valueOf(1)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        jPanel1.add(windowLengthSpinner, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 321, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
    HelpHandler.getHandler().showHelpDialogForKey("rnaseqhelp."+ID, null);
}//GEN-LAST:event_helpLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner minQualSpinner;
    private javax.swing.JSpinner windowLengthSpinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public TMTrimmerArguments getArguments() {
        TMTrimmerArguments args = new TMTrimmerArguments("SLIDINGWINDOW"); 
        args.put("requiredQuality", minQualSpinner.getValue());  
        args.put("windowLength", windowLengthSpinner.getValue()); 
        return args;
    }

    @Override
    public void setArguments(TMTrimmerArguments args) {
        this.minQualSpinner.setValue( Float.parseFloat(args.get("requiredQuality").toString()) );
        this.windowLengthSpinner.setValue( Integer.parseInt(args.get("windowLength").toString()) );
    }
}
