/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressDialog.java
 *
 * Created on 26.08.2011, 13:14:11
 */
package de.mpimp.golm.robin.GUI;

import de.mpimp.golm.robin.GUI.RobinMainGUI;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author marc
 */
public class ProgressDialog extends javax.swing.JDialog {

    /** Creates new form ProgressDialog */
    public ProgressDialog(java.awt.Frame parent, boolean modal, boolean unDecorated) {
        super(parent, modal);
        this.setUndecorated(unDecorated);
        initComponents();
        centerOnParent();
    }
    
    @Override
    public void setVisible(boolean state) { 
        if (this.getOwner() instanceof RobinMainGUI) {
            ((RobinMainGUI) this.getOwner()).setGrayedOut(state);
        } else if (this.getOwner() instanceof javax.swing.JFrame ) {
            ((javax.swing.JFrame) this.getOwner()).getGlassPane().setVisible(state);
        }
        super.setVisible(state);
    }
    
    @Override
    public void dispose() {
        if (this.getOwner() instanceof RobinMainGUI) {
            ((RobinMainGUI) this.getOwner()).setGrayedOut(false);
        } else if (this.getOwner() instanceof javax.swing.JFrame ) {
            ((javax.swing.JFrame) this.getOwner()).getGlassPane().setVisible(false);
        }
        super.dispose();
    }
    
    
    

    public int getProgress() {
        return progressBar.getValue();
    }

    public void setProgress(int p) {
        this.progressBar.setValue(p);
        this.repaint();
    }

    public void setText(String text) {
        this.text.setText(text);
        this.repaint();
    }
    
    public void centerOnParent() {
        int x;
        int y;

        // Find out our parent 
        Container myParent = getParent();
        
        if (myParent == null || !myParent.isShowing()) return;
        
        Point topLeft = myParent.getLocationOnScreen();
        Dimension parentSize = myParent.getSize();

        Dimension mySize = getSize();

        if (parentSize.width > mySize.width) {
            x = ((parentSize.width - mySize.width) / 2) + topLeft.x;
        } else {
            x = topLeft.x;
        }

        if (parentSize.height > mySize.height) {
            y = ((parentSize.height - mySize.height) / 2) + topLeft.y;
        } else {
            y = topLeft.y;
        }

        setLocation(x, y);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressBar = new javax.swing.JProgressBar();
        text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 4, 10);
        getContentPane().add(progressBar, gridBagConstraints);

        text.setFont(text.getFont().deriveFont(text.getFont().getSize()-1f));
        text.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 10, 0);
        getContentPane().add(text, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables

    public void setIndeterminate(boolean state) {
        this.progressBar.setIndeterminate(state);
    }
}
