/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RobinWorkflowPanel.java
 *
 * Created on 09.03.2010, 23:19:23
 */

package de.mpimp.golm.robin.GUI;

import java.io.Serializable;

/**
 *
 * @author marc
 */
public class RobinWorkflowPanel extends javax.swing.JPanel {

    /** Creates new form RobinWorkflowPanel */
    public RobinWorkflowPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        stepPanel = new javax.swing.JPanel();
        previousStepButton = new javax.swing.JButton();
        nextStepButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        stepPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stepPanel.setLayout(new java.awt.GridBagLayout());

        previousStepButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/mpimp/golm/robin/resources/GoToPrevious.png"))); // NOI18N
        previousStepButton.setText(org.openide.util.NbBundle.getMessage(RobinWorkflowPanel.class, "RobinWorkflowPanel.previousStepButton.text")); // NOI18N
        previousStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousStepButtonActionPerformed(evt);
            }
        });
        stepPanel.add(previousStepButton, new java.awt.GridBagConstraints());

        nextStepButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/mpimp/golm/robin/resources/GoToNextHS.png"))); // NOI18N
        nextStepButton.setText(org.openide.util.NbBundle.getMessage(RobinWorkflowPanel.class, "RobinWorkflowPanel.nextStepButton.text")); // NOI18N
        nextStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 18;
        stepPanel.add(nextStepButton, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stepPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .add(stepPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void previousStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousStepButtonActionPerformed

}//GEN-LAST:event_previousStepButtonActionPerformed

    private void nextStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStepButtonActionPerformed

}//GEN-LAST:event_nextStepButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextStepButton;
    private javax.swing.JButton previousStepButton;
    private javax.swing.JPanel stepPanel;
    // End of variables declaration//GEN-END:variables

}
