/*
 * RobinReleaseNotesDialog.java
 *
 * Created on 20. November 2008, 06:48
 */

package de.mpimp.golm.robin.GUI;

import de.mpimp.golm.common.utilities.Utilities;
import java.awt.Dimension;
import java.awt.Point;
import de.mpimp.golm.robin.misc.RobinUtilities;

/**
 *
 * @author  marc
 */
public class RobinReleaseNotesDialog extends javax.swing.JDialog {

    /** Creates new form RobinReleaseNotesDialog */
    public RobinReleaseNotesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // initialize the text label from file
        String notes = Utilities.loadString(getClass().getResourceAsStream("/de/mpimp/golm/robin/RELEASE_NOTES.html"));
        releaseNotesLabel.setText(notes);
        this.centerOnParent();
        this.setVisible(true);
    }
    
    private void centerOnParent() {
        Dimension parentDim = getParent().getSize();
        Point parentLoc = getParent().getLocation();
        Dimension myDim = getSize();
        
        int myX = (parentDim.width / 2 + parentLoc.x) - myDim.width / 2;
        int myY = (parentDim.height / 2 + parentLoc.y) - myDim.height / 2;
        
        setLocation(myX, myY);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        showOnStartBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        releaseNotesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText(org.openide.util.NbBundle.getMessage(RobinReleaseNotesDialog.class, "RobinReleaseNotesDialog.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        showOnStartBox.setBackground(new java.awt.Color(255, 255, 255));
        showOnStartBox.setSelected(true);
        showOnStartBox.setText(org.openide.util.NbBundle.getMessage(RobinReleaseNotesDialog.class, "RobinReleaseNotesDialog.showOnStartBox.text")); // NOI18N
        showOnStartBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOnStartBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        releaseNotesLabel.setBackground(new java.awt.Color(255, 255, 255));
        releaseNotesLabel.setText(org.openide.util.NbBundle.getMessage(RobinReleaseNotesDialog.class, "RobinReleaseNotesDialog.releaseNotesLabel.text")); // NOI18N
        releaseNotesLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        releaseNotesLabel.setOpaque(true);
        jScrollPane1.setViewportView(releaseNotesLabel);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(showOnStartBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 391, Short.MAX_VALUE)
                .add(jButton1))
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, showOnStartBox)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton1)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void showOnStartBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOnStartBoxActionPerformed
    ((RobinMainGUI)this.getParent()).setShowReleaseNotes(showOnStartBox.isSelected());// TODO add your handling code here:
}//GEN-LAST:event_showOnStartBoxActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel releaseNotesLabel;
    private javax.swing.JCheckBox showOnStartBox;
    // End of variables declaration//GEN-END:variables

}
