/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RNASeqMappingResultPanel.java
 *
 * Created on 10.10.2011, 10:31:15
 */
package de.mpimp.golm.robin.GUI.RNASeq.mapping;

import de.mpimp.golm.common.logger.SimpleLogger;
import java.awt.Color;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author marc
 */
public class RNASeqMappingResultPanel extends javax.swing.JPanel {

    /** Creates new form RNASeqMappingResultPanel */
    public RNASeqMappingResultPanel(String sampleName, ChartPanel distChart, ChartPanel mismatchChart, String ResultText) {
        initComponents();
        this.sampleNameLabel.setText("Sample: "+sampleName);
        this.distChartPanel.add(distChart);
        this.distChartPanel.revalidate();
        this.mismatchChartPanel.add(mismatchChart);
        this.mismatchChartPanel.revalidate();
        this.summaryTextArea.append(ResultText);
        
        SimpleLogger.getLogger(true).logMessage("Mapping stats for sample "+sampleName+"\n"+ResultText);
        
    }
    
    public void setWarning(boolean b) {
        if (b) {
            summaryTextArea.setForeground(Color.RED);
        } else {
            summaryTextArea.setForeground(Color.WHITE);
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distChartPanel = new javax.swing.JPanel();
        sampleNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryTextArea = new javax.swing.JTextArea();
        mismatchChartPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        distChartPanel.setMinimumSize(new java.awt.Dimension(260, 125));
        distChartPanel.setPreferredSize(new java.awt.Dimension(260, 125));
        distChartPanel.setLayout(new javax.swing.BoxLayout(distChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        sampleNameLabel.setFont(sampleNameLabel.getFont().deriveFont((sampleNameLabel.getFont().getStyle() | java.awt.Font.ITALIC) | java.awt.Font.BOLD));
        sampleNameLabel.setText(org.openide.util.NbBundle.getMessage(RNASeqMappingResultPanel.class, "RNASeqMappingResultPanel.sampleNameLabel.text")); // NOI18N

        jScrollPane1.setBorder(null);

        summaryTextArea.setColumns(20);
        summaryTextArea.setLineWrap(true);
        summaryTextArea.setRows(5);
        summaryTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(summaryTextArea);

        mismatchChartPanel.setLayout(new javax.swing.BoxLayout(mismatchChartPanel, javax.swing.BoxLayout.LINE_AXIS));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(sampleNameLabel)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                    .add(mismatchChartPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(distChartPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(sampleNameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(distChartPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mismatchChartPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .add(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel distChartPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mismatchChartPanel;
    private javax.swing.JLabel sampleNameLabel;
    private javax.swing.JTextArea summaryTextArea;
    // End of variables declaration//GEN-END:variables

    
}
